### PR TITLE
Updated the favorites tab

### PR DESCRIPTION
**Pull request by tlauver**
Updated UI, removed load button so  it loads on select now, moved around some attributes (which means old favorites won't work anymore), moved components around

### CODE REVIEW

**Comment by csmoore** [comment]
I get a crash/exception when I try to delete favorite (hit delete button):

image

(favoriteset in null)

**Comment by csmoore** [comment]
If I import the Favorites.json file twice I get the favorites repeated (same unique id) 👍 

image

**Comment by tlauver** [comment]
I'll look into the delete favorites issue.  For the duplicate favorites, do you want me to check for the id before importing and prevent adding if the id is already there?  Or do you want to have duplicates?

**Comment by csmoore** [comment]
You can overwrite it if it has the same unique id - just so we don't end up with 2 with the same unique id

**Comment by csmoore** [comment]
A few minor issue noted above, but looks and works really good.

**Pull request merged**
