### PR TITLE
Jrm/remove xceed depends

### PR DESCRIPTION
**Pull request by jmccausland**

### CODE REVIEW

**Comment by jmccausland** [comment]
@csmoore please review and let me know if you need anything else

**Comment by csmoore** [comment]
Thanks @jmccausland - I'll test it out in a bit

**Comment by csmoore** [comment]
Changes generally look good:

image

The only issue I am seeing is that the time is not available - and oddly setting `ShowTime="True" ` seems to have no effect so still looking into this.

image

I was also hoping this will fully resolve our dark mode issue with this control but perhaps there is some additional styling needed to support this.

**Comment by jmccausland** [comment]
@csmoore what build of Pro are you on? Pro 2.3 build 15769 has time and theme.

**Comment by csmoore** [comment]
@jmccausland - I was testing on 2.1 but it does look different on 2.3:

image

**Comment by csmoore** [comment]
Just to summarize, things look good, except for these 2 issues:

1. Time can't be set in Pro 2.1 (only Date) - Time works on 2.2, 2.3 
    a. I tried a few things (like setting `ShowTime="true"`) but couldn't seem to get it to show
    b. @lfunkhouser would have to make the call if this limitation is OK on 2.1
2. Speed is throwing exception when bound variable is null - we use null to flag that this label should not be displayed/set (this can probably be fixed)
```
System.Windows.Data Error: 6 : 'SystemConvertConverter' converter failed to convert value '<null>' (type '<null>'); fallback value will be used, if available. BindingExpression:Path=SymbolAttributeSet.LabelAttributes.Speed; DataItem='MilitarySymbolDockpaneViewModel' (HashCode=66028312); target element is 'NumberUpDownControl' (Name='speedUpDown'); target property is 'CurrentValue' (type 'Int32') InvalidCastException:'System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
```

**Comment by csmoore** [comment]
@jmccausland - do you know if there is some way to get the time control to show up/work on 2.1 with the DateTimePicker, that is the primary impediment to merging this change.

**Comment by jmccausland** [comment]
@csmoore do you have a 2.1 dev machine I can remote into? We only work with the latest version.

**Comment by jmccausland** [comment]
@csmoore ShowTime="True" should work even though it looks like it's true by default clear back to Jan 3rd, 2017.  Which is before 2.1 I believe.

**Comment by csmoore** [comment]
@jmccausland - sorry no 2.1 VM , I did try adding `ShowTime="True"` to no effect but I can look at again on 2.1 to see what could be going wrong.

**Comment by elinz** [comment]
@jmccausland @csmoore I'm creating a VM for you guys to test this. The VM will have:
- OS 8.1 x64 since both Pro 2.1 and VS 2013 support this OS.
- Pro 2.1 final with standard license
- VS 2013 Professional

**Comment by csmoore** [comment]
@elinz - many thanks for setting this up. One minor change/correction - we only use VS2013 to build ArcMap 10.3 - for Pro we use VS2015.

@jmccausland - the other [issue above is the exception](https://github.com/Esri/military-symbology/pull/335#issuecomment-455621960) being thrown in the new spinner control - not sure if you have a chance to look at that also

**Comment by elinz** [comment]
@csmoore Thanks. I will install VS2015.

**Comment by jmccausland** [comment]
@csmoore can you provide repro steps for the speed exception?

**Comment by csmoore** [comment]
The behavior I am seeing with MSE on 2.1 looks the same behavior I am seeing in Pro so seems like a bug with the control on that version:

image

**Comment by jmccausland** [comment]
@csmoore updown control current value is nullable now, enjoy

**Comment by csmoore** [comment]
Tested from `\MilitarySymbolEditor\Testing\Jrm-remove-xceed-depends\36\` only issues noted are **on Pro 2.1 only**:

1. For the Date Time Valid/Expired fields, User can only pick the Date from the DateTime control and must manually enter the time in the text box (Note: this is also an issue in Pro 2.1 on the table view with DateTime fields).
2. DateTime control does not honor dark mode (this was also an existing issue with the previous controls)

@lfunkhouser @dfoll recommended merging and this known limitation will be documented in release notes.

Screen shot of manually setting the time on Pro 2.1:
image

**Review by csmoore — APPROVED** [review]
Many thanks for this enhancement, only 2.1 limitation is noted in https://github.com/Esri/military-symbology/pull/335#issuecomment-456926468 - I'll merge after updating the readme

**Pull request merged**
