### PR TITLE
Final code drop for #394

### PR DESCRIPTION
**Pull request by sumitzarkar**
- Implemented #394

### CODE REVIEW

**Comment by csmoore** [comment]
@sumitzarkar @ashutoshverma-ct  - Just a question on the CoordinateConversion dependency in this project - it looks like is using the older CoordinateConversion dependency ( vs. the newer version at: https://github.com/Esri/coordinate-conversion-addin-dotnet/tree/Pro2.6 )

Just checking that this is expected - in case there is just something wrong with my configuration for building:

image

**Comment by csmoore** [comment]
Can you do the PR into this branch instead: https://github.com/Esri/military-symbology/tree/Pro2.6 

Compare/New PR: https://github.com/Esri/military-symbology/compare/Pro2.6...CT-Ticket394

Sorry I was unclear on the branch and didn't catch this earlier.

**Comment by ashutoshverma-ct** [comment]
@csmoore 

> @sumitzarkar @ashutoshverma-ct - Just a question on the CoordinateConversion dependency in this project - it looks like is using the older CoordinateConversion dependency ( vs. the newer version at: https://github.com/Esri/coordinate-conversion-addin-dotnet/tree/Pro2.6 )
> 
> Just checking that this is expected - in case there is just something wrong with my configuration for building:

Yes, it is using the older CoordinateConversion dependency for now. Should we update the reference?

**Comment by csmoore** [comment]
@ashutoshverma-ct - yes, please switch the the project/library version from the "Pro2.6" branch. Sorry again, I was unclear on the branch/version to use. Thanks

**Comment by csmoore** [comment]
Closing this PR unmerged - we will review/merge the new PR #396 into the Pro2.6 branch - thanks and sorry for the confusion

**Comment by ashutoshverma-ct** [comment]
@csmoore 

> @ashutoshverma-ct - yes, please switch the the project/library version from the "Pro2.6" branch. Sorry again, I was unclear on the branch/version to use. Thanks

No issues, we will update the code. Thanks

**Pull request closed without merging**
