### PR TITLE
Minor unit test changes

### PR DESCRIPTION
**Pull request by csmoore**

### CODE REVIEW

**Comment by csmoore** [comment]
@jmccausland - if you could have a look to see if you have any ideas for how we can unit test code that has dependencies on Pro.Project - we are not sure how else to unit test other than mocking.

**Comment by csmoore** [comment]
Forgot to update the readme with instructions to run #56 - please hold

**Comment by jmccausland** [comment]
I have not been able to or seen anyone doing unit tests with Pro without mocking.  Interesting post here.[https://geonet.esri.com/thread/163979]( https://geonet.esri.com/thread/163979 ``)

**Comment by csmoore** [comment]
@tlauver - this is now ready for review/test/merge

**Pull request merged**
